### ISSUE TITLE
Memory Requirements

### ISSUE THREAD

**Issue by ctSkennerton** [dparks1134/DBB#1]
Hey Donovan,

what kind of memory usage are you seeing? I just tried running DBB and it only processed 0.18% of the scaffolds and used up all of the memory on my server (128Gb). Is the number of scaffolds I'm trying to run through very (too) large?

```
Reading scaffolds.
    Scaffolds: 3076723

  Reading BAM file.
    Reference scaffolds >= 1000 bps: 353171

  Processing reference scaffolds.
    Processed 637 of 353171 (0.18%) scaffolds.
```

**Comment by donovan-h-parks** [comment]
Hey Connor,

It does indeed seem to be eating up A LOT of memory. Must admit I never even bothered to look and am a little shocked to see how bad it is. This has something to do with the multiprocessing being done. I'll have to look into it. In the meantime, you can safely bump up the minimum scaffold size used by the preprocess command to 5k. In general, I don't recommend trying to bin contigs below this size. The default for the next steps is set to 5k.

**Comment by ctSkennerton** [comment]
I just tried setting the contig length to 5000 and with only one cpu and it still used up all the memory on the system after ~200 contigs.  I'm wondering if this is a `pysam` issue as I've had some bad memory leaks from it in the past? Basically every time I see this it's from pysam. On my system I'm running pysam 0.8.0, what's the version that your running at ACE?

**Comment by donovan-h-parks** [comment]
I'm running pysam 0.7.7. This does sound like it is at least partially a pysam issue. DBB should more-or-less max out its required memory usage one it has read in the scaffolds. At lease for me, once DBB starts "Processing reference scaffolds" the memory usage doesn't increase.

**Comment by ctSkennerton** [comment]
Yep, it's a version issue with pysam. Version 0.7.7 has stable memory consumption at ~5Gb. It is also running much faster than before too

**Comment by donovan-h-parks** [comment]
I've pushed an update to DBB. This should reduce the memory requirements, though it can still be a few Gb/cpu. A more substantial rework of the code is needed to really address this issue.
